async function viewCourse(){
  await migrateLegacyRoster(state.courseId);
  const {c,students,sessions}=await courseData();
  const rosters=await rostersForCourse(c.id);
  if(students.length) await ensureDefaultLayout(c.id);
  const layouts=students.length?await courseLayouts(c.id):[];
  const active=layouts.find(l=>l.id===c.activeLayoutId)||layouts[0];
  const ended=sessions.filter(s=>s.status==='ended');
  const activeRoster=rosters.find(r=>r.id===c.activeRosterId);
  const rosterCard=`<div class="card"><div class="row"><div><h3 class="sectiontitle">Rosters</h3><div class="muted small">A course can contain several imported rosters. Choose which one is active for new sessions and assessment.</div></div><div class="toolbar"><select id="activeRoster" class="input compact"><option value="">— No active roster —</option>${rosters.map(r=>`<option value="${r.id}" ${r.id===c.activeRosterId?'selected':''}>${esc(r.name)} · ${r.studentCount??0}</option>`).join('')}</select><label class="btn primary">Import Excel / CSV<input id="rosterFile" type="file" accept=".xlsx,.xls,.csv" hidden></label>${activeRoster?'<button class="btn" id="renameRoster">Rename</button>':''}</div></div>${rosters.length?`<div class="muted small" style="margin-top:8px">${rosters.map(r=>`${r.id===c.activeRosterId?'<strong>Active:</strong> ':''}${esc(r.name)} (${r.studentCount??0})${r.sourceFile?` · ${esc(r.sourceFile)}`:''}`).join(' &nbsp; | &nbsp; ')}</div>`:'<div class="hint">Create/import a roster before starting a session. Excel .xlsx/.xls and CSV are supported, with column mapping before import.</div>'}</div>`;
  let body='';
  if(students.length){
    body=`<div class="card"><div class="row"><div><h3 class="sectiontitle">Registration panel order</h3><div class="muted small">Use automatic alphabetical ordering or a saved manual classroom layout.</div></div><select id="panelOrder" class="input compact"><option value="manual" ${c.panelOrder==='manual'||!c.panelOrder?'selected':''}>Manual layout</option><option value="first_asc" ${c.panelOrder==='first_asc'?'selected':''}>First name · A → Z</option><option value="first_desc" ${c.panelOrder==='first_desc'?'selected':''}>First name · Z → A</option><option value="last_asc" ${c.panelOrder==='last_asc'||c.panelOrder==='alphabetical'?'selected':''}>Surname · A → Z</option><option value="last_desc" ${c.panelOrder==='last_desc'?'selected':''}>Surname · Z → A</option></select></div></div><div class="card"><div class="row"><div><h3 class="sectiontitle">Saved classroom layouts</h3><div class="muted small">Layouts apply to the active roster only.</div></div><div class="toolbar"><select id="layoutSelect" class="input compact">${layouts.map(l=>`<option value="${l.id}" ${active?.id===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select><button class="btn" id="newLayout">New</button><button class="btn" id="duplicateLayout">Duplicate</button><button class="btn" id="renameLayout">Rename</button><button class="btn danger" id="deleteLayout" ${layouts.length<=1?'disabled':''}>Delete</button></div></div></div><div class="two"><div class="card"><div class="row"><div><h3 class="sectiontitle">Active roster & manual layout</h3><div class="muted small">The panel below shows only students in the active roster.</div></div><button class="btn" id="saveManualOrder">Save active layout</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Position</th><th>Student</th><th>ID</th><th>Email</th><th></th></tr></thead><tbody>${students.map(s=>`<tr><td><input class="input orderInput" type="number" min="1" max="${students.length}" value="${(s.seat??0)+1}" data-id="${s.id}"></td><td>${esc(fullName(s))}</td><td>${esc(s.externalId)}</td><td>${esc(s.email||'')}</td><td><button class="btn ghost studentDetail" data-id="${s.id}">View</button></td></tr>`).join('')}</tbody></table></div></div><div class="card"><h3 class="sectiontitle">Sessions</h3><div class="muted small" style="margin-bottom:8px">Each session preserves its roster and layout snapshot.</div>${sessions.slice().reverse().map(se=>`<div class="sessionrow"><div><strong>${esc(se.title)}</strong><div class="muted small">${new Date(se.startedAt).toLocaleString()} · ${esc(se.status)}${se.rosterNameSnapshot?` · roster: ${esc(se.rosterNameSnapshot)}`:''}${se.layoutNameSnapshot?` · layout: ${esc(se.layoutNameSnapshot)}`:''}</div></div><div class="toolbar"><span class="badge">${esc(se.status)}</span><button class="btn openSession" data-id="${se.id}">${se.status==='ended'?'Edit':'Open'}</button></div></div>`).join('')||'<div class="muted">No sessions yet.</div>'}</div></div></div>`;
  }else{
    body='<div class="card"><h3>Course created</h3><p class="muted">Import an Excel/CSV roster above. You will map the file columns before the roster is saved.</p></div>';
  }
  return `<div class="stack"><div class="card"><div class="row"><div><h2>${esc(c.name)}</h2><div class="muted">${students.length} students · ${ended.length} completed sessions · ${activeRoster?`active roster: ${esc(activeRoster.name)}`:'no roster assigned'}</div></div><div class="toolbar"><button class="btn" id="editCourse">Settings</button><button class="btn primary" id="startSession" ${students.length?'':'disabled'}>Start session</button></div></div></div>${rosterCard}${body}</div>`;
}
