const DB_NAME='class-participation-db-v2',DB_VERSION=4;let db;let applyingRemote=false;let syncTimer=null;const SYNC_STORES=['courses','students','sessions','events','attendance','notes','grades','transcriptSegments','layouts','rosters'];let state={view:'courses',courseId:null,sessionId:null,lastEventId:null,toast:null,modal:null,qualityTarget:null,sessionEditAction:'add',arrangeMode:false,importDraft:null,syncStatus:'local'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uuid=()=>crypto.randomUUID(),nowISO=()=>new Date().toISOString(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number(n||0).toFixed(2),pct=n=>Math.round((n||0)*100)+'%';
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;for(const [n,k] of [['courses','id'],['students','id'],['sessions','id'],['events','id'],['attendance','id'],['notes','id'],['grades','id'],['transcriptSegments','id'],['layouts','id'],['rosters','id'],['syncQueue','qid']])if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:k})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function os(n,m='readonly'){return db.transaction(n,m).objectStore(n)}function all(n){return new Promise((res,rej)=>{const r=os(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function get(n,id){return new Promise((res,rej)=>{const r=os(n).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function rawPut(n,o){return new Promise((res,rej)=>{const r=os(n,'readwrite').put(o);r.onsuccess=()=>res(o);r.onerror=()=>rej(r.error)})}function rawDel(n,id){return new Promise((res,rej)=>{const r=os(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function enqueueSync(store,op,id,payload=null){if(applyingRemote||!SYNC_STORES.includes(store))return;await rawPut('syncQueue',{qid:uuid(),store,op,id,payload,clientAt:nowISO()});scheduleSync()}
async function put(n,o){const out=await rawPut(n,o);await enqueueSync(n,'put',o.id,o);return out}async function del(n,id){await rawDel(n,id);await enqueueSync(n,'delete',id,null)}
function accessKey(){return localStorage.getItem('class-participation-access-key')||''}function setAccessKey(v){if(v)localStorage.setItem('class-participation-access-key',v);else localStorage.removeItem('class-participation-access-key')}
async function cloudRequest(method='GET',body=null){const key=accessKey();if(!key)throw Object.assign(new Error('Cloud access key required'),{code:401});const r=await fetch('/api/sync',{method,headers:{'Content-Type':'application/json','X-App-Key':key},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(r.status===401)throw Object.assign(new Error('Invalid cloud access key'),{code:401});if(!r.ok)throw new Error(`Cloud sync failed (${r.status})`);return r.json()}
async function applyRemoteRecords(records){applyingRemote=true;try{for(const rec of records||[]){if(!SYNC_STORES.includes(rec.entity_type))continue;if(rec.deleted)await rawDel(rec.entity_type,rec.entity_id);else if(rec.payload)await rawPut(rec.entity_type,rec.payload)}}finally{applyingRemote=false}}
async function localSnapshotMutations(){const out=[];for(const store of SYNC_STORES){for(const item of await all(store))out.push({store,op:'put',id:item.id,payload:item})}return out}
async function syncNow(showToast=false){if(!navigator.onLine){state.syncStatus='offline';render();return}if(!accessKey()){state.syncStatus='locked';render();return}state.syncStatus='syncing';render();try{const q=await all('syncQueue');const remote=await cloudRequest('GET');let mutations=q.map(x=>({store:x.store,op:x.op,id:x.id,payload:x.payload}));if((remote.records||[]).length===0){const snapshot=await localSnapshotMutations();const keyed=new Map(snapshot.map(m=>[`${m.store}:${m.id}`,m]));for(const m of mutations)keyed.set(`${m.store}:${m.id}`,m);mutations=[...keyed.values()]}const data=mutations.length?await cloudRequest('POST',{mutations}):remote;for(const x of q)await rawDel('syncQueue',x.qid);await applyRemoteRecords(data.records);state.syncStatus='synced';if(showToast)toast('Cloud sync complete');else render()}catch(e){state.syncStatus=e.code===401?'locked':'error';render();if(showToast)alert(e.message)}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncNow(false),600)}
async function connectCloud(){const current=accessKey();const key=prompt('Enter the Class Participation cloud access key',current);if(key===null)return;if(!key.trim()){setAccessKey('');state.syncStatus='locked';return render()}setAccessKey(key.trim());await syncNow(true)}

function toast(t){state.toast=t;render();setTimeout(()=>{state.toast=null;render()},1100)}
function fullName(s){return `${s.firstName||''} ${s.lastName||''}`.trim()}
function cmpText(a,b){return String(a||'').localeCompare(String(b||''),undefined,{sensitivity:'base',numeric:true})}
function compareFirst(a,b){return cmpText(a.firstName,b.firstName)||cmpText(a.lastName,b.lastName)}
function compareLast(a,b){return cmpText(a.lastName,b.lastName)||cmpText(a.firstName,b.firstName)}
function orderLabel(mode){return ({manual:'manual',first_asc:'first name A–Z',first_desc:'first name Z–A',last_asc:'surname A–Z',last_desc:'surname Z–A'})[mode]||'manual'}
function sortStudents(students,course,forceManual=false){const copy=students.slice(),mode=forceManual?'manual':(course?.panelOrder||'manual');if(mode==='first_asc')return copy.sort(compareFirst);if(mode==='first_desc')return copy.sort((a,b)=>compareFirst(b,a));if(mode==='last_asc'||mode==='alphabetical')return copy.sort(compareLast);if(mode==='last_desc')return copy.sort((a,b)=>compareLast(b,a));return copy.sort((a,b)=>(a.seat??0)-(b.seat??0))}
function gridProfile(n){if(n<=12)return{min:150,density:'spacious'};if(n<=24)return{min:130,density:'comfortable'};if(n<=40)return{min:112,density:'comfortable'};if(n<=60)return{min:100,density:'standard'};if(n<=80)return{min:90,density:'compact'};return{min:82,density:'dense'}}
function normalizeHeader(h){return String(h||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
async function rostersForCourse(courseId){return (await all('rosters')).filter(r=>r.courseId===courseId).sort((a,b)=>cmpText(a.name,b.name))}
async function getCourseStudents(courseId){const c=await get('courses',courseId),allStudents=(await all('students')).filter(s=>s.courseId===courseId);if(c?.activeRosterId)return allStudents.filter(s=>s.rosterId===c.activeRosterId);return allStudents}
async function migrateLegacyRoster(courseId){const c=await get('courses',courseId);if(!c)return null;let rs=await rostersForCourse(courseId);if(rs.length){if(!c.activeRosterId){c.activeRosterId=rs[0].id;await put('courses',c)}return rs[0]}const legacy=(await all('students')).filter(s=>s.courseId===courseId);if(!legacy.length)return null;const r={id:uuid(),courseId,name:'Roster 1',sourceFile:'Legacy data',studentCount:legacy.length,createdAt:nowISO(),updatedAt:nowISO()};await put('rosters',r);for(const st of legacy){st.rosterId=r.id;await put('students',st)}c.activeRosterId=r.id;for(const l of (await all('layouts')).filter(l=>l.courseId===courseId&&!l.rosterId)){l.rosterId=r.id;await put('layouts',l)}await put('courses',c);return r}
function guessMapping(headers){const n=headers.map(normalizeHeader),find=(xs)=>{for(const x of xs){const i=n.indexOf(x);if(i>=0)return headers[i]}return''};return{externalId:find(['student_id','studentid','id','id_alumno','id_estudiante','matricula','student_number','student_no']),firstName:find(['first_name','firstname','nombre','given_name','name']),lastName:find(['last_name','lastname','surname','apellidos','apellido','family_name']),email:find(['email','e_mail','correo','correo_electronico']),photoUrl:find(['photo','photo_url','picture','image','foto','foto_url'])}}
async function parseRosterFile(file){const ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='csv'){const rows=csvParse(await file.text());if(!rows.length)throw new Error('The file is empty.');const headers=rows.shift().map(x=>String(x||'').trim()),data=rows.filter(r=>r.some(x=>String(x||'').trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));return{headers,data,sheetName:'CSV'}}if(!['xlsx','xls'].includes(ext))throw new Error('Use .xlsx, .xls or .csv.');if(typeof XLSX==='undefined')throw new Error('Excel reader is unavailable. Connect to the internet once and reload the app.');const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:false,raw:false}),sheetName=wb.SheetNames[0],sheet=wb.Sheets[sheetName],matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});if(!matrix.length)throw new Error('The workbook is empty.');const headers=matrix.shift().map((x,i)=>String(x||`Column ${i+1}`).trim()),data=matrix.filter(r=>r.some(x=>String(x||'').trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));return{headers,data,sheetName}}
function mappingSelect(id,label,headers,value,required=false){return `<label>${esc(label)}${required?' *':''}<select class="input" id="${id}"><option value="">— Not mapped —</option>${headers.map(h=>`<option value="${esc(h)}" ${h===value?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`}
async function showRosterImport(file){try{const parsed=await parseRosterFile(file);if(parsed.data.length<1)throw new Error('The roster contains no student rows.');if(parsed.data.length>100)throw new Error(`Maximum 100 students. This file contains ${parsed.data.length}.`);const guessed=guessMapping(parsed.headers);state.importDraft={fileName:file.name,parsed,guessed};state.modal=`<div class="modalback"><div class="modal wide"><div class="row"><div><h3>Import roster</h3><div class="muted small">${esc(file.name)} · ${parsed.data.length} rows · sheet: ${esc(parsed.sheetName)}</div></div><button class="btn" id="closeModal">Cancel</button></div><div class="formgrid"><label>Roster name<input class="input" id="rosterName" value="${esc(file.name.replace(/\.(xlsx|xls|csv)$/i,''))}"></label>${mappingSelect('mapFirst','First name',parsed.headers,guessed.firstName,true)}${mappingSelect('mapLast','Surname / last name',parsed.headers,guessed.lastName,true)}${mappingSelect('mapId','Student ID',parsed.headers,guessed.externalId,false)}${mappingSelect('mapEmail','Email',parsed.headers,guessed.email,false)}${mappingSelect('mapPhoto','Photo URL',parsed.headers,guessed.photoUrl,false)}</div><div class="hint">Required: first name and surname. Other fields are optional. The original headings may be anything; map them here before importing.</div><div class="tablewrap"><table class="table"><thead><tr>${parsed.headers.slice(0,6).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${parsed.data.slice(0,5).map(r=>`<tr>${parsed.headers.slice(0,6).map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="row"><div class="muted small">Preview: first 5 rows</div><button class="btn primary" id="confirmRosterImport">Import and assign to course</button></div></div></div>`;render()}catch(err){alert(err.message||String(err))}}
async function commitRosterImport(){const d=state.importDraft;if(!d)return;const first=$('#mapFirst').value,last=$('#mapLast').value;if(!first||!last)return alert('Map both First name and Surname.');const name=$('#rosterName').value.trim()||'Roster',map={externalId:$('#mapId').value,firstName:first,lastName:last,email:$('#mapEmail').value,photoUrl:$('#mapPhoto').value},r={id:uuid(),courseId:state.courseId,name,sourceFile:d.fileName,studentCount:d.parsed.data.length,mapping:map,createdAt:nowISO(),updatedAt:nowISO()};await put('rosters',r);for(let i=0;i<d.parsed.data.length;i++){const row=d.parsed.data[i],val=k=>map[k]?String(row[map[k]]??'').trim():'';await put('students',{id:uuid(),courseId:state.courseId,rosterId:r.id,externalId:val('externalId')||`S${String(i+1).padStart(3,'0')}`,firstName:val('firstName'),lastName:val('lastName'),email:val('email'),photoUrl:val('photoUrl'),seat:i,createdAt:nowISO()})}const c=await get('courses',state.courseId);c.activeRosterId=r.id;c.activeLayoutId=null;c.panelOrder='manual';await put('courses',c);state.importDraft=null;state.modal=null;await ensureDefaultLayout(state.courseId);toast(`${r.studentCount} students imported into ${r.name}`);render()}

async function courseLayouts(courseId){const c=await get('courses',courseId),items=(await all('layouts')).filter(l=>l.courseId===courseId);if(!c?.activeRosterId)return items.filter(l=>!l.rosterId).sort((a,b)=>cmpText(a.name,b.name));const scoped=[];for(const l of items){if(l.rosterId===c.activeRosterId)scoped.push(l);else if(!l.rosterId){l.rosterId=c.activeRosterId;await put('layouts',l);scoped.push(l)}}return scoped.sort((a,b)=>cmpText(a.name,b.name))}
async function ensureDefaultLayout(courseId){const c=await get('courses',courseId);let ls=await courseLayouts(courseId);if(ls.length)return ls;const students=sortStudents(await getCourseStudents(courseId),{panelOrder:'manual'},true);const l={id:uuid(),courseId,rosterId:c.activeRosterId||null,name:'Default',positions:students.map((s,i)=>({studentId:s.id,position:i})),createdAt:nowISO(),updatedAt:nowISO()};await put('layouts',l);c.activeLayoutId=l.id;await put('courses',c);return[l]}
async function saveActiveLayout(courseId){const c=await get('courses',courseId);await ensureDefaultLayout(courseId);const students=sortStudents(await getCourseStudents(courseId),{panelOrder:'manual'},true);let l=c.activeLayoutId?await get('layouts',c.activeLayoutId):null;if(!l){l=(await courseLayouts(courseId))[0];c.activeLayoutId=l.id;await put('courses',c)}l.positions=students.map((s,i)=>({studentId:s.id,position:i}));l.updatedAt=nowISO();await put('layouts',l);return l}
async function activateLayout(layoutId){const l=await get('layouts',layoutId);if(!l)return;const c=await get('courses',l.courseId),students=await getCourseStudents(l.courseId),pos=new Map((l.positions||[]).map(x=>[x.studentId,x.position]));students.sort((a,b)=>(pos.has(a.id)?pos.get(a.id):9999)-(pos.has(b.id)?pos.get(b.id):9999));for(let i=0;i<students.length;i++){students[i].seat=i;await put('students',students[i])}c.activeLayoutId=l.id;c.panelOrder='manual';await put('courses',c)}
async function snapshotSessionLayout(sessionId){const sess=await get('sessions',sessionId),c=await get('courses',sess.courseId),students=sortStudents(await getCourseStudents(sess.courseId),c);const l=c.activeLayoutId?await get('layouts',c.activeLayoutId):null;sess.panelOrderSnapshot=c.panelOrder||'manual';sess.layoutIdSnapshot=l?.id||null;sess.layoutNameSnapshot=l?.name||null;const r=c.activeRosterId?await get('rosters',c.activeRosterId):null;sess.rosterIdSnapshot=c.activeRosterId||null;sess.rosterNameSnapshot=r?.name||null;sess.layoutSnapshot=students.map((s,i)=>({studentId:s.id,position:i}));await put('sessions',sess)}

async function seed(){return}
